language: cpp
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-multilib libc6-dev-i386 lib32stdc++6 lib32z1-dev
  - CHECKOUT_DIR=$PWD && cd .. && $CHECKOUT_DIR/checkout-deps.sh && cd $CHECKOUT_DIR
script:
  - mkdir build-clang-opt && cd build-clang-opt
  - python ../configure.py --enable-optimize
  - ambuild
  - ./tests/testrunner/testrunner
