language: cpp
compiler:
  - clang
before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-multilib libc6-dev-i386 lib32stdc++6 lib32z1-dev
  - sudo apt-get install g++-4.8 g++-4.7 g++-4.6
  - CHECKOUT_DIR=$PWD && cd .. && $CHECKOUT_DIR/checkout-deps.sh && cd $CHECKOUT_DIR
script:
  - mkdir build-clang-opt && cd build-clang-opt
  - python ../configure.py --enable-optimize
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..

  - mkdir build-clang-debug && cd build-clang-debug
  - python ../configure.py --enable-debug
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..

  - mkdir build-gcc46-opt && cd build-clang-opt
  - CC="gcc-4.6" CXX="g++-4.6" python ../configure.py --enable-optimize
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..

  - mkdir build-gcc46-debug && cd build-clang-debug
  - CC="gcc-4.6" CXX="g++-4.6" python ../configure.py --enable-debug
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..

  - mkdir build-gcc47-opt && cd build-clang-opt
  - CC="gcc-4.7" CXX="g++-4.7" python ../configure.py --enable-optimize
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..

  - mkdir build-gcc47-debug && cd build-clang-debug
  - CC="gcc-4.7" CXX="g++-4.7" python ../configure.py --enable-debug
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..

  - mkdir build-gcc48-opt && cd build-clang-opt
  - CC="gcc-4.8" CXX="g++-4.8" python ../configure.py --enable-optimize
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..

  - mkdir build-gcc48-debug && cd build-clang-debug
  - CC="gcc-4.8" CXX="g++-4.8" python ../configure.py --enable-debug
  - ambuild
  - ./tests/testrunner/testrunner
  - cd ..
